### ISSUE TITLE
Navigation won't create space between with justify content, and images in my 3 column grid wont be the same size

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/modularity-mindfulness#4]
@HannahDelaney

- I had Mackenzie help me with the placement of my Nav. However, it seems that it still won't have space between. (I feel really bad constantly bugging her so I came to you! Sorry!)

- The 3 images in my 3 column grid doesn't seem to be the same size. I tried playing around with the widths of them, but when I do that, it ends up messing up the symmetry of the gaps. Any suggestions?

<img width="602" alt="Screen Shot 2020-09-22 at 1 26 45 PM" src="https://user-images.githubusercontent.com/54897840/94023828-abea7080-fd84-11ea-8fb1-83b2d90ae5b5.png">

**Comment by Sophia-Villamayor** [comment]
@hellachella

**Comment by HannahDelaney** [comment]
Haha don't apologize — that is literally both of our jobs!

To start you off, there are a lot of spare margins on your `.viewing`, `.gravel` and `.symbolism` classes. If you get rid of those lines, things will already start to align a bit better.

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney 
You're right! It looks a lot better :) I'm just still a little confused on what to do next to get the images aligned. Sorry!

**Comment by HannahDelaney** [comment]
Although, looking more at the way you've built this, I think you might be better off to put a `margin: 0` on all those elements, and define the needed spacing by putting some padding on the left and right sides of your main tag, as well as a `gap: 1rem;`. That will allow you to have cleaner control over the spacing.

Then there's that Gravel picture...the images are displaying at different sizes at the moment. You need to establish the width of the grid columns in the main grid. Try adding `grid-template-columns: repeat(3, 1fr);` to your main tag.

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney 
OMG Thank you sooooo much!!!! <3333333
Just one more thing, I promise! I've been having trouble with the space between the Nav. I'm not sure as to how to fix it. Any ideas?
